<?php

namespace NoxLogic\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorizedKeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizedKeysRepository extends EntityRepository
{
}
