<?php

namespace NoxLogic\AppBundle\Repository;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;
use NoxLogic\AppBundle\Entity\Repository;

/**
 * RepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRepository extends EntityRepository
{
    /**
     * @param int $limit
     *
     * @return Repository[]
     */
    function findRandomRepositories($limit = 10)
    {
        $qb = $this->createQueryBuilder('r');
        $qb
            ->select('r', 'o', 'rights')
            ->addSelect('RAND() as HIDDEN rand')
            ->join('r.owner', 'o')
            ->join('r.rights', 'rights')
            ->orderBy('rand')
            ->setMaxResults($limit)
        ;

        return $qb->getQuery()->getArrayResult();
    }

    function findByUserNameAndRepo($userName, $repoName)
    {
        $repo = $this->findOneByName($repoName);
        if (! $repo) {
            return null;
        }

        // Check if owner is username
        if ($repo->getOwner()->getUsernameCanonical() != $userName) {
            return null;
        }

        return $repo;
    }

}
