<?php

namespace NoxLogic\AppBundle\Repository;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;

/**
 * RepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRepository extends EntityRepository
{

    function findByUserNameAndRepo($userName, $repoName) {
        $repo = $this->findOneByName($repoName);
        if (! $repo) {
            throw new EntityNotFoundException();
        }

        // Check if owner is username
        if ($repo->getOwner()->getUsernameCanonical() != $userName) {
            throw new EntityNotFoundException();
        }

        return $repo;
    }

}
